// <auto-generated />
using Api_Maquinaria.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api_Maquinaria.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261005193808_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Api_Maquinaria.Models.Equipment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Equipments");

                    b.HasData(
                        new
                        {
                            Id = "eq-1",
                            Code = "BOM-001",
                            Location = "Sala de máquinas",
                            Name = "Bomba centrífuga 01",
                            Status = "Operativo"
                        },
                        new
                        {
                            Id = "eq-2",
                            Code = "COM-002",
                            Location = "Taller",
                            Name = "Compresor A2",
                            Status = "En mantenimiento"
                        },
                        new
                        {
                            Id = "eq-3",
                            Code = "TAB-003",
                            Location = "Depósito",
                            Name = "Tablero eléctrico Norte",
                            Status = "Operativo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
